### ISSUE TITLE
Add overlay for About-Page

### ISSUE THREAD

**Issue by floisloading** [yunity/yunity-webapp#12]

**Comment by ghost** [comment]
I'm stuck trying to implement a modal dialog, resulting in TypeError: compileData is undefined;
compileData is a variable instantiated by some part of the mcgrea.ngStrap module, and I can't figure out what's going wrong. Help please!

**Comment by ghost** [comment]
I managed to sort it out after we changed from using angular-strap to angular-ui-bootstrap.
It's not pretty, but it works.
