### ISSUE TITLE
Come up with a way of generating natural text translations

### ISSUE THREAD

**Issue by ghost** [yunity/yunity-webapp#17]
The translation dictionary used right now (e.g. lang-en_US.json) only supports single-line translations, whereas for uses like the About page, we want chunks of text. The idea is to set up a generate-translations.js script that points the translation module to useful chunks of text.

**Comment by floisloading** [comment]
The translation directory can also translate whole passages of text, I thought...

**Comment by ghost** [comment]
It can, but they need to be on a single line, so not very human-readable. Would it make sense, for large chunks of text (e.g. the About page, or some sort of Help/FAQ that we might want to implement eventually), to use templates, and have their URLs in the translation .json files perhaps?

**Comment by floisloading** [comment]
The usual file format for translations is .po (or .pot). You can add comments, show progress etc. Unfortunately, I have no experience in it. I found a few useful links:
-  PoEdit, tool for translating: https://poedit.net/
- po2json: https://github.com/mikeedwards/po2json
- PO-loader for webpack: https://github.com/perchlayer/po-loader

I have no clue what will be the right workflow. Angular-Translate does not support po files, so maybe it would be good to export po-Files as json (maybe via webpack?) to keep the translations up to date. @jsavinc could you mention this in the dev Meeting tomorrow? Cause I will leave tomorrow...
