### ISSUE TITLE
Minimise asking browser for location

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-webapp#21]
At the moment each time I go from page to page on webapp/webapp-mobile the site reasks my browser for my location. The default option in firefox only remembers for one time, and asks again each time the page changes.

My concern is that users don't like popups and we shouldn't irritate them. We should minimise the number of times we ask.

A few thoughts:
- could do geoip via a backend call to get approx location without a popup dialog
- could have an explicit "go to my location" button, in which case they would expect the popup
- could save the location to localStorage when requested to it won't ask again

Thoughts?

**Comment by nicksellen** [comment]
It is also currently delaying rendering the map until the popup question has been answered, it would seem preferable to show the map regardless.

**Comment by floisloading** [comment]
I like the approach with geoip - we should leave this card in the backend, until this function is implemented in the backend, then switch to the approach, @nicksellen suggested.
