### ISSUE TITLE
Add footbar to select which categories will be shown on the map

### ISSUE THREAD

**Issue by floisloading** [yunity/yunity-webapp#22]
In the draft, there is a footer with symbols https://www.justinmind.com/usernote/tests/17600986/17612021/17612023/index.html#/screens/6f43d301-dd48-4f2e-adea-2dda868d5895

It should be added as a directive an (second task) be connected to the map.

**Comment by ghost** [comment]
Working on it. I'll just copy the sidebar code and rework it.
Are they meant to filter search results as well? Currently I'm calling the directive "mapfilter", but maybe "itemfilter" would be more general?

**Comment by NerdyProjects** [comment]
Not neccessary anymore because of ongoing design decision / results
