### ISSUE TITLE
Let Angular throw Error-Messages/Exceptions when a problem occurs

### ISSUE THREAD

**Issue by floisloading** [yunity/yunity-webapp#3]
Right now, when Angular misses a variable (e.g. typo), the site just doesn't load. It would be nice to have error messages for debugging.

**Comment by maackle** [comment]
you mean how a misspelled `{{ variable }}` just fails silently? or a syntax error that causes the entire page to not load? can you give an example?

**Comment by floisloading** [comment]
exactly. A misspelled variable, a controller or something else, that just doesn't load fails silently...

**Comment by nicksellen** [comment]
I'm not sure you can detect misspelled variables as you are allowed to access unknown/null/undefined properties on an object in javascript.

But many errors show exceptions in the js console, I thought all errors that cause the whole site not to load should be doing this.

The default handler can be overriden to have custom behaviour (e.g. post the exception back to the server). Here's an implementation from another project:

Here's an implementation I used in another project:

```
app.factory('$exceptionHandler', ['$injector', function($injector) {
  var $cookies;
  return function(exception, cause) {
    if (!$cookies) $cookies = $injector.get('$cookies');
    jQuery.ajax({
      method: 'POST',
      url: '/api/events/exceptions',
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify({
        message: exception.message,
        stacktrace: exception.stack,
        cause: cause
      }),
      headers: {
        'X-XSRF-TOKEN': $cookies['XSRF-TOKEN']
      }
    });
    throw exception;
  };
}]);
```

**Comment by floisloading** [comment]
Nice :) @maackle could you integrate and test that? Would fit best in the webapp-common imo

**Comment by NerdyProjects** [comment]
status here?
